# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore Github_CI.slnx
    - name: Build
      run: dotnet build Github_CI.slnx --configuration Release --no-restore
    - name: Run Unit Tests
      run: dotnet test --project Tests/UnitTests/UnitTests.csproj --configuration Release --no-build --no-restore --verbosity normal --retry-failed-tests 3
#    - name: Run Integration Tests
#      run: dotnet test --project Tests/IntegrationTests/IntegrationTests.csproj --configuration Release --no-build --no-restore --verbosity normal --retry-failed-tests 3
